Solr/Controllers/SetupController.cs
using Newtonsoft.Json.Linq;
using Solr.BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Solr.Controllers
{
    [RoutePrefix("api/Setup")]
    public class SetupController : ApiController
    {
        [Route("GetSchemaFields")]
        public List<Schema> GetSchemaFields()
        {
            List<Schema> schemaFields = new List<Schema>();
            try
            {
                schemaFields = Schema.Get();
            }
            catch (Exception ex)
            {
                Utilities.SolrException.WriteError(ex);
            }
            return schemaFields;
        }

        [Route("AddSchemaField")]
        public bool PostAddSchemaField(JObject value)
        {
            try
            {
                Schema schema = new Schema();
                var schemaName = value["Name"]?.Value<string>();

                if (schemaName.Substring(0, 3) == "LU_")
                {
                    schema.Name = schemaName;
                    schema.Type = value["Type"]?.Value<string>();
                    schema.Stored = value["Stored"]?.Value<string>();
                    schema.Indexed = value["Indexed"]?.Value<string>();
                    schema.DefaultValue = value["DefaultValue"]?.Value<string>();
                    schema.AddFieldInLucene();
                    schema.SaveInDB();
                }
                else if (schemaName.Substring(0, 3) == "DB_")
                {
                    schema.Name = schemaName;
                    schema.Type = value["Type"]?.Value<string>();
                    schema.Stored = "Yes";
                    schema.Indexed = "No";
                    schema.SaveInDB();
                }
                else
                {
                    schema.Name = schemaName;
                    schema.Type = value["Type"]?.Value<string>();
                    schema.Stored = value["Stored"]?.Value<string>();
                    schema.Indexed = value["Indexed"]?.Value<string>();
                    schema.DefaultValue = value["DefaultValue"]?.Value<string>();
                    schema.AddFieldInLucene();
                    schema.SaveInDB();
                }
                return true;
            }
            catch (Exception ex)
            {
                Utilities.SolrException.WriteError(ex);
            }
            return false;
        }

        [Route("DeleteSchemaField")]
        public bool PostDeleteSchemaField(JObject value)
        {
            try
            {
                int id = value["ID"].Value<int>();
                Schema schema = Schema.Get(id);
                schema.Name = value["Name"].Value<string>();
                schema.Delete();
                return true;
            }
            catch (Exception ex)
            {
                Utilities.SolrException.WriteError(ex);
            }
            return false;
        }

        [Route("IngestFiles")]
        public void PostIngestFiles(JObject value)
        {
            try
            {
                string folderPath = value["Directory"].Value<string>();
                string searchPattern = value["SearchPattern"].Value<string>();
                BusinessLayer.SolrOperation.IngestFiles(folderPath, searchPattern);
            }
            catch (Exception ex)
            {
                Utilities.SolrException.WriteError(ex);
            }
        }

        [Route("DeleteFiles")]
        public void PostDeleteFiles(JObject value)
        {
            try
            {
                var requestString = $"http://localhost:8983/solr/gettingStarted/update?stream.body=<delete><query>*:*</query></delete>&commit=true";
                SolrOperation.LuceneRequest(requestString);
            }
            catch (Exception ex)
            {
                Utilities.SolrException.WriteError(ex);
            }
        }

    }
}

Solr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="/bower_components/angular-material/angular-material.css">
    <link rel="stylesheet" href="https://material.angularjs.org/latest/docs.css">    
    <link rel="stylesheet" type="text/css" href="/bower_components/ng-prettyjson/dist/ng-prettyjson.min.css">
    <link href="/bower_components/angular-material-data-table/dist/md-data-table.min.css" rel="stylesheet" type="text/css" />
    
    <script src="/bower_components/jquery/dist/jquery.js"></script>
    <script src="/bower_components/angular/angular.js"></script>
    <script src="/bower_components/angular-route/angular-route.js"></script>
    <script src="/Scripts/linq.js"></script>

    <script src="/bower_components/angular-animate/angular-animate.min.js"></script>
    <script src="/bower_components/angular-sanitize/angular-sanitize.js"></script>
    <script src="/bower_components/angular-aria/angular-aria.min.js"></script>
    <script src="/bower_components/angular-messages/angular-messages.min.js"></script>
    <script src="/bower_components/angular-material/angular-material.min.js"></script>
    <script src="/bower_components/angular-material/modules/js/svgAssetsCache/svgAssetsCache.js"></script>
    <script type="text/javascript" src="/bower_components/ng-prettyjson/dist/ng-prettyjson.min.js"></script>
    <script type="text/javascript" src="/bower_components/angular-material-data-table/dist/md-data-table.min.js"></script>

    <script src="/Scripts/App/app.js"></script>
    <script src="/Scripts/App/setupCtrl.js"></script>
    <script src="/Scripts/App/ruleCtrl.js"></script>

</head>
<body ng-app="Solr" role="document">    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Classification", "Setup", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Setup", "Setup", "Home")</li>
                    <li>@Html.ActionLink("Rule","Rule", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()        
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>